// try catch finally throw

try{
    //block of code is tried
}catch(error){
    // if any error occurs in the try block, the error is catched by this block
    //we can also display what error has occured like console.log(error);
}finally{
    //this block of code is run regardless of the error
}